version: '3.4'

services:
  catalogdb:
    container_name: catalog_db
    restart: always
    ports: 
        - "27017:27017"
    volumes:
        - mongo_data:/data/db 

  basketdb:
    container_name: basket_db
    restart: always
    ports: 
        - "6379:6379"

  discountdb:
    container_name: discountdb
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  gemma.catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "LoggerConfigOption:OverrideSource=Microsoft"
      - "LoggerConfigOption:OutputTemplate=[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {NewLine} {Properties} {NewLine} {NewLine} {Message} {Exception}"
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings:Database=ProductDb"
      - "DatabaseSettings:Collection=Products"
    depends_on:
      - catalogdb
    ports:
      - "8000:80" 
    
  gemma.basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "LoggerConfigOption:OverrideSource=Microsoft"
      - "LoggerConfigOption:OutputTemplate=[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {NewLine} {Properties} {NewLine} {NewLine} {Message} {Exception}"
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcClient:DiscountUrl=http://discount.grpc"
    depends_on:
      - basketdb
    ports:
      - "8001:80"

  gemma.discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "LoggerConfigOption:OverrideSource=Microsoft"
      - "LoggerConfigOption:OutputTemplate=[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {NewLine} {Properties} {NewLine} {NewLine} {Message} {Exception}"
      - "DiscountDb:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"
  
  mongo_express:
    container_name: catalougedb_mongoexpress
    environment:
       - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
       - ME_CONFIG_MONGODB_SERVER=catalogdb
    depends_on:
       - catalogdb
    ports:
       - "8081:8081" 

  redis-commander:
    container_name: basketdb_viewer
    restart: always
    depends_on:
        - basketdb
    environment:
        - REDIS_HOST=basketdb:6379
    ports:
        - 8082:8081

  pgadmin:
    container_name: discountdb_manager
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@speedpack.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
