version: '3.4'

services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis:alpine
  discountdb:
    image: postgres 
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  rabbitmq:
    image: rabbitmq:3.11-management-alpine

  gemma.catalog.api:
    image: ${DOCKER_REGISTRY-}gemmacatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Gemma.Catalog.API/Dockerfile
  
  gemma.basket.api:
    image: ${DOCKER_REGISTRY-}gemmabasketapi
    build:
      context: .
      dockerfile: Services/Basket/Gemma.Basket.API/Dockerfile
  
  gemma.discount.grpc:
    image: ${DOCKER_REGISTRY-}gemmadiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Gemma.Discount.GRPC/Dockerfile

  gemma.order.api:
    image: ${DOCKER_REGISTRY-}gemmaorderapi
    build:
      context: .
      dockerfile: Services/Order/Gemma.Order.Api/Dockerfile

  mongo_express:
    image: mongo-express
  redis-commander:
    image: rediscommander/redis-commander:latest
  pgadmin:
    image: dpage/pgadmin4  

volumes:
  mongo_data: 
  postgres_data:
  pgadmin_data:



