version: '3.4'

services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis:alpine
  discountdb:
    image: postgres 

  gemma.catalog.api:
    image: ${DOCKER_REGISTRY-}gemmacatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Gemma.Catalog.API/Dockerfile
  
  gemma.basket.api:
    image: ${DOCKER_REGISTRY-}gemmabasketapi
    build:
      context: .
      dockerfile: Services/Basket/Gemma.Basket.API/Dockerfile
  
  gemma.discount.grpc:
    image: ${DOCKER_REGISTRY-}gemmadiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Gemma.Discount.GRPC/Dockerfile

  mongo_express:
    image: mongo-express
  redis-commander:
    image: rediscommander/redis-commander:latest
  pgadmin:
    image: dpage/pgadmin4  

  
volumes:
  mongo_data: 
  postgres_data:
  pgadmin_data:


