version: '3.4'

services:
  catalogdb:
    image: mongo

  gemma.catalog.api:
    image: ${DOCKER_REGISTRY-}gemmacatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Gemma.Catalog.API/Dockerfile

  mongo_express:
    image: mongo-express
volumes:
  mongo_data: 
